// Banco editorial: cada pareja se presenta como una unidad de texto e imagen.
// Los niveles se vinculan por la misión vigente, sin alterar su consigna.
const banco = [
  [
    ['ferrocarril-1869', 'El comienzo fue entre dos estaciones', 'El 1 de enero de 1869 se inauguró el primer tramo ferroviario de Uruguay, entre Bella Vista y Las Piedras. Era un ferrocarril, no un metro. Aquella conexión permite pensar una pregunta que sigue vigente: ¿qué lugares conviene unir primero para que una red resulte útil?', 'Elegir conexiones útiles antes de ampliar la red.', 'AFE, historia ferroviaria', 'https://www.afe.com.uy/historia.php', 'Dos estaciones y una locomotora esquemática sobre una vía, con la fecha 1869.'],
    ['penarol-barrio', 'El tren también construyó barrios', 'El desarrollo ferroviario dejó huellas fuera de las vías. En Peñarol, la instalación de talleres y estación en torno a 1890–1891 estuvo acompañada por viviendas para trabajadores y personal jerárquico. Una red de transporte puede relacionar hogares, empleos y servicios, y transformar la organización de un barrio.', 'Una estación forma parte de un entorno urbano.', 'Intendencia de Montevideo, patrimonio de Peñarol', 'https://montevideo.gub.uy/tipo/area-tematica/emprendimientos-empleo-y-economia/centro-economico-territorial-penarol-0', 'Taller, estación y viviendas unidos por senderos en un esquema urbano.'],
  ],
  [
    ['londres-1863', 'Londres abrió camino en 1863', 'El 10 de enero de 1863 abrió en Londres el primer ferrocarril subterráneo del mundo, entre Paddington y Farringdon Street. La red actual nació de aquella primera conexión. Su historia recuerda que una gran red puede crecer por etapas, a partir de un recorrido inicial bien elegido.', 'Una red puede desarrollarse gradualmente.', 'Transport for London, historia del Underground', 'https://foi.tfl.gov.uk/FOI-0773-2324/TUBE160%20Heritage%20Leaflet.pdf', 'Una línea inicial de 1863 que se ramifica en un diagrama ficticio.'],
    ['buenos-aires-1913', 'El pionero latinoamericano está cerca', 'Buenos Aires inauguró su Línea A el 1 de diciembre de 1913. El primer recorrido unía Plaza de Mayo con Plaza Miserere y fue el primer subterráneo de Latinoamérica. Durante 1914 la línea se extendió hacia otros barrios: ampliar una conexión existente también puede aumentar su utilidad.', 'Las extensiones incorporan nuevos destinos.', 'Gobierno de Buenos Aires, historia de la Línea A', 'https://buenosaires.gob.ar/gcaba_historico/jefaturadegabinete/movilidad/subte/nuestra-historia/nuestra-historia/linea-a', 'Dos extremos de una línea de 1913 y una extensión marcada para 1914.'],
  ],
  [
    ['frecuencia-100', 'Un tren cada cien segundos', 'En 2017, la línea Victoria de Londres aumentó su servicio de hora pico a 36 trenes por hora. Eso equivale a un intervalo medio de 100 segundos. La curiosidad muestra una idea importante: la capacidad de una línea depende tanto de cada tren como de la frecuencia del servicio.', 'Distinguir capacidad por vehículo y por hora.', 'TfL, informe del programa de inversiones 2017–2018', 'https://content.tfl.gov.uk/tfl-investment-programme-report-q3-2017-18.pdf', 'Reloj de cien segundos y tres trenes igualmente espaciados.'],
    ['capacidad-coordinada', 'Más frecuencia requiere coordinación', 'Para aumentar la frecuencia de la línea Victoria, Londres modificó señalización, trenes, alimentación eléctrica y vías. No bastaba con sumar vehículos. En una red real, transportar más personas requiere coordinar varios elementos para que los trenes puedan circular y detenerse con seguridad y con un servicio confiable.', 'Identificar límites de infraestructura antes de añadir capacidad.', 'TfL, revisión del proyecto World Class Capacity', 'https://content.tfl.gov.uk/pic-20170628-item07-lu-world-class-capacity.pdf', 'Cuatro piezas conectadas: tren, señal, energía y vía.'],
  ],
  [
    ['tranvia-1906', 'Montevideo ya viajaba con electricidad', 'Los tranvías eléctricos comenzaron a funcionar en Montevideo en 1906. Forman parte de la historia del transporte urbano uruguayo, aunque no eran una red de metro. Recordarlos ayuda a distinguir dos ideas: usar electricidad describe la energía del vehículo; ser tranvía o metro describe también cómo circula.', 'Electrificación y tipo de sistema son conceptos diferentes.', 'Municipio E, historia del transporte de la Unión', 'https://municipioe.montevideo.gub.uy/sites/municipioe/files/junio_09_zona_6.pdf', 'Tranvía esquemático con cable aéreo sobre una calle, rotulado 1906.'],
    ['tres-trazados', 'Un metro puede ver el cielo', 'Un metro no tiene que circular siempre bajo tierra. Puede tener tramos subterráneos, elevados o en superficie. Una característica decisiva es que opera en infraestructura independiente del tránsito de calles y de peatones. Un tranvía, en cambio, puede compartir parte de su recorrido con la circulación urbana.', 'La separación del tránsito importa más que estar bajo tierra.', 'UITP–UNIFE, definición de transporte ferroviario urbano', 'https://www.uitp.org/wp-content/uploads/sites/7/2026/05/202309_URP_definition-of-urban-rail.pdf', 'Un tren esquemático en túnel, viaducto y superficie protegida.'],
  ],
  [
    ['acceso-anden', 'Llegar al andén no siempre basta', 'Una estación puede ofrecer ascensores hasta el andén y todavía tener un escalón o una separación al entrar al tren. Por eso, Transport for London distingue entre acceso sin escalones hasta el andén y hasta el vehículo. Una conexión útil debe considerar el recorrido completo de las personas.', 'La accesibilidad debe mantenerse durante todo el viaje.', 'TfL, acceso sin escalones', 'https://tfl.gov.uk/travel-information/improvements-and-projects/step-free-access?intcmp=1954', 'Recorrido de calle a ascensor, andén y tren, con una separación indicada.'],
    ['acceso-estacion', 'El viaje empieza antes de la estación', 'El IPCC destaca que el transporte público y la infraestructura para caminar o andar en bicicleta pueden favorecer viajes con menores emisiones. Las estaciones forman parte de ese conjunto. Ubicar una parada cerca de los destinos ayuda, pero también importa que existan recorridos cómodos y seguros para llegar hasta ella.', 'Considerar el acceso a la red además del trayecto en tren.', 'IPCC, AR6, resumen para responsables de políticas', 'https://www.ipcc.ch/report/ar6/wg3/chapter/summary-for-policymakers/', 'Estación vinculada con vereda, bicicletero, viviendas y servicios.'],
  ],
  [
    ['ocupacion-tren', 'La ocupación también cuenta', 'El IPCC señala que los ómnibus y trenes con alta ocupación pueden reducir considerablemente las emisiones por pasajero y kilómetro. El resultado cambia según cuántas personas viajan y qué energía se utiliza. Por eso, una red ambientalmente útil necesita servicios que respondan a viajes reales, no solamente vehículos nuevos.', 'Relacionar demanda atendida con emisiones por pasajero.', 'IPCC, AR6, capítulo 10', 'https://www.ipcc.ch/report/ar6/wg3/downloads/report/IPCC_AR6_WGIII_Chapter10.pdf', 'Dos trenes iguales con ocupación visual diferente y sin cifras de ahorro.'],
    ['electricidad-2024', 'Importa de dónde viene la electricidad', 'Según el MIEM, el 99% de la generación eléctrica de Uruguay provino de fuentes renovables en 2024. Ese dato se refiere a electricidad, no a toda la energía utilizada en el país. Al evaluar transporte eléctrico, conocer cómo se genera su electricidad es parte de la comparación ambiental.', 'Diferenciar matriz eléctrica y consumo total de energía.', 'MIEM, Balance Energético Preliminar 2024', 'https://www.gub.uy/ministerio-industria-energia-mineria/comunicacion/noticias/uruguay-vuelve-registrar-niveles-record-fuentes-renovables-matriz-generacion', 'Enchufe conectado con agua, viento, biomasa y sol; fecha 2024.'],
  ],
  [
    ['mapa-beck', 'Un mapa no siempre mide distancias', 'El mapa de Harry Beck, publicado en Londres en 1933, usaba líneas horizontales, verticales y diagonales, con estaciones espaciadas de manera uniforme. No reproducía exactamente la geografía. Esa simplificación ayudaba a entender recorridos y conexiones: en un diagrama de red, cercanía visual y distancia real pueden ser diferentes.', 'Leer conexiones sin asumir que el dibujo está a escala.', 'London Transport Museum, mapa de Harry Beck', 'https://library.ltmuseum.co.uk/portal/Default/en-GB/RecordView/Index/106', 'La misma red ficticia como mapa geográfico y diagrama esquemático.'],
    ['intercambio-lineas', 'Una combinación abre más destinos', 'La Línea A de Buenos Aires conecta con otras líneas de subte y con el Ferrocarril Sarmiento en Plaza Miserere. Estas combinaciones permiten continuar viajes que una sola línea no cubre. Para pensar una red, no alcanza con contar estaciones: también importa qué recorridos quedan conectados entre sí.', 'Evaluar destinos alcanzables mediante combinaciones.', 'Gobierno de Buenos Aires, conexiones de la Línea A', 'https://buenosaires.gob.ar/gcaba_historico/jefaturadegabinete/movilidad/subte/nuestra-historia/nuestra-historia/linea-a', 'Dos líneas y un ferrocarril unidos por un nodo de intercambio.'],
  ],
  [
    ['frenado-energia', 'Frenar puede recuperar energía', 'Algunos trenes eléctricos utilizan frenado regenerativo: recuperan parte de la energía del movimiento y la devuelven al sistema eléctrico. En el metro de Londres, esa energía puede ayudar a mover otro tren. Su aprovechamiento depende de los equipos y de cómo funciona la red; no toda la energía se recupera.', 'La eficiencia también depende de cómo opera el sistema.', 'TfL, informe anual 2015–2016', 'https://content.tfl.gov.uk/tfl-annual-report-2015-16.pdf', 'Tren frenando, línea eléctrica y otro tren acelerando con flechas de energía.'],
    ['ciclo-vida', 'La obra también deja una huella', 'Para comparar transportes no alcanza con mirar lo que emiten durante un viaje. El IPCC distingue también emisiones asociadas a fabricar vehículos y construir infraestructura. Una evaluación completa considera esas etapas junto con el funcionamiento del servicio. Tener motores eléctricos no convierte automáticamente una red en un sistema sin impacto.', 'Pensar en el ciclo de vida completo.', 'IPCC, alcance de las emisiones del transporte', 'https://www.ipcc.ch/report/ar6/wg3/figures/chapter-10/figure-10-1', 'Materiales, construcción, operación y mantenimiento en secuencia.'],
  ],
  [
    ['clima-proteccion', 'El clima también afecta al metro', 'Las inundaciones, tormentas y olas de calor pueden interrumpir redes de transporte. Londres incluye estos riesgos en su planificación y contempla medidas como sistemas de refrigeración y jardines que gestionan el agua de lluvia. Diseñar una red duradera también exige pensar cómo seguirá funcionando cuando cambien las condiciones.', 'La confiabilidad incluye preparación ante riesgos.', 'TfL, adaptación al cambio climático', 'https://tfl.gov.uk/corporate/about-tfl/adapting-to-climate-change?intcmp=72525', 'Red bajo sol y lluvia con un escudo de protección y drenaje.'],
    ['caneria-tunel', 'El agua no viene solamente de la lluvia', 'En su revisión de riesgos de inundación, Transport for London identificó las roturas de cañerías como una amenaza importante para el Underground. La lección es sorprendente: una red subterránea comparte la ciudad con otras infraestructuras. Cuidar estaciones y túneles requiere conocer también lo que sucede alrededor.', 'Una red depende de otros servicios urbanos.', 'TfL, revisión de riesgos y adaptación', 'https://tfl.gov.uk/corporate/about-tfl/adapting-to-climate-change?intcmp=72525', 'Corte esquemático de calle, cañería con fuga y túnel separado.'],
  ],
  [
    ['estudio-ferroviario', 'Estudiar no significa inaugurar', 'En abril de 2025, el MTOP presentó un estudio sobre un posible servicio ferroviario de pasajeros para el área metropolitana, con atención al corredor de la ruta 5. Un estudio de factibilidad analiza si una propuesta puede funcionar. No significa que ese servicio ya esté construido o circulando.', 'Distinguir propuesta, estudio y servicio operativo.', 'MTOP, estudio de factibilidad ferroviaria', 'https://www.gub.uy/ministerio-transporte-obras-publicas/comunicacion/noticias/se-presento-estudio-factibilidad-para-implementar-servicio-ferroviario', 'Etapas separadas de estudio, obra y operación, con 2025 visible.'],
    ['alternativas-2026', 'Elegir el sistema adecuado', 'En marzo de 2026, el MTOP publicó una comparación de ómnibus de tránsito rápido, tren ligero y metro ligero para corredores metropolitanos. Analizaron capacidad, funcionamiento, inserción urbana y costos iniciales. Elegir transporte no consiste solamente en escoger un vehículo: implica encontrar una solución adecuada para cada corredor.', 'Comparar demanda, espacio, operación y costo.', 'MTOP, análisis comparativo de alternativas modales', 'https://www.gub.uy/ministerio-transporte-obras-publicas/comunicacion/noticias/analisis-comparativo-alternativas-modales-para-area-metropolitana-montevideo', 'Tres alternativas de transporte ante el mismo corredor, sin ganadora universal.'],
  ],
];

// Variantes generales C/D por tema. El orden coincide con la misión de cada nivel.
const ampliacionGeneral = [
  [
    ['excursion-fonoelectrica-1937', 'Un tren con relato en vivo', 'En 1937, el Ferrocarril Central del Uruguay estrenó excursiones «fonoeléctricas». Dos locutores relataban el viaje desde un coche transmisor, y los pasajeros los escuchaban por parlantes distribuidos en los salones. La experiencia recuerda que el ferrocarril también fue una forma de pasear, conocer lugares y compartir información durante el recorrido.', 'Reconocer usos recreativos y culturales del ferrocarril uruguayo.', 'AFE, Historia Ferroviaria del Uruguay, 1937', 'https://www.afe.com.uy/historia.php', 'Dos locutores transmiten el relato del viaje a los parlantes de los vagones de una excursión ferroviaria de 1937.'],
    ['senales-1931', 'Las señales también tienen historia', 'En 1931, el Ferrocarril Central del Uruguay instaló señalización eléctrica con luces de tres posiciones en el tramo de vía doble entre Central, Empalme Tablada y Peñarol. Las señales servían para gobernar la marcha de los trenes. La historia ferroviaria también incluye tecnologías de coordinación que los pasajeros no siempre ven.', 'Identificar la señalización como parte de la infraestructura ferroviaria.', 'AFE, Historia Ferroviaria del Uruguay, 1931', 'https://www.afe.com.uy/historia.php', 'Esquema de dos vías y una señal ferroviaria junto a Central, Empalme Tablada y Peñarol, con fecha 1931.'],
  ],
  [
    ['budapest-1896', 'Un pionero bajo una avenida', 'Budapest inauguró su ferrocarril subterráneo del Milenio el 2 de mayo de 1896. Fue el primero de Europa continental y se diseñó desde el inicio para funcionar con electricidad. Su recorrido bajo la avenida Andrássy muestra cómo una obra de transporte puede quedar ligada a la historia y al patrimonio de una ciudad.', 'Relacionar las redes históricas con su entorno urbano.', 'BKV, historia del ferrocarril del Milenio', 'https://www.bkv.hu/en/content/living-history-underground-budapests-millenium-underground-turns-130-05052026', 'Tren eléctrico en un túnel bajo una avenida de Budapest, en un esquema fechado en 1896.'],
    ['tokio-1927', 'Tokio empezó con Asakusa y Ueno', 'El 30 de diciembre de 1927 abrió el primer tramo de subterráneo de Tokio, entre Asakusa y Ueno. Fue el primer metro de Asia, según su operador. El proyecto había comenzado a construirse en 1925: antes del primer viaje hubo una etapa de obras, distinta del funcionamiento cotidiano de la red.', 'Diferenciar construcción e inauguración de una línea.', 'Tokyo Metro, History', 'https://www.tokyometro.jp/lang_en/corporate/profile/history/index.html', 'Cronología de la construcción en 1925 y la inauguración en 1927 del tramo de Tokio entre Asakusa y Ueno.'],
  ],
  [
    ['parada-y-frecuencia', 'Una parada larga afecta a otros trenes', 'El tiempo que un tren permanece detenido en una estación influye en la capacidad de la línea. Un informe de la MTA explica que los trenes siguientes deben mantener una distancia segura; si las detenciones se alargan, pueden aumentar los intervalos. Por eso, el tiempo de ascenso y descenso también cuenta.', 'Reconocer el tiempo de parada como límite de capacidad.', 'MTA, Subway Speed and Capacity Review', 'https://www.mta.info/document/13046', 'Un tren se detiene en una estación mientras el siguiente espera a distancia, con un reloj que representa el intervalo.'],
    ['pasillo-continuo-r211', 'Un pasillo entre vagones', 'Los R211 de pasillo continuo presentados en Nueva York en 2023 incorporan paredes flexibles, parecidas a un acordeón, que conectan sus vagones. Esa unión permite circular por el interior entre coches. El ejemplo muestra que organizar un tren también consiste en pensar cómo se distribuyen y se mueven sus pasajeros.', 'Relacionar distribución interior y circulación de pasajeros.', 'Kawasaki, presentación de los R211', 'https://global.kawasaki.com/en/corp/newsroom/news/detail/?f=20230306_7827', 'Dos vagones de metro unidos por un fuelle cerrado y un pasillo interior continuo para los pasajeros.'],
  ],
  [
    ['rodadura-metro', 'Hay metros con neumáticos', 'En el metro de Ciudad de México hay trenes con ruedas metálicas y otros de rodadura neumática, que utilizan neumáticos. Así, dos vehículos llamados «metro» pueden tener soluciones técnicas diferentes. Comparar redes requiere mirar más que su nombre: también cuentan las vías, los equipos y la infraestructura compatible.', 'Distinguir el tipo de servicio de la tecnología de rodadura.', 'STC Ciudad de México, Conformación de un tren', 'https://www.metro.cdmx.gob.mx/operacion/conformacion-de-un-tren', 'Comparación esquemática de una rueda de acero sobre un riel y un neumático sobre una pista de rodadura de metro.'],
    ['tranvia-tren-2018', 'Un vehículo entre dos redes', 'En 2018 comenzó a funcionar un servicio de tranvía-tren entre Sheffield y Rotherham, en Inglaterra. Sus vehículos pueden circular tanto por la red de tranvías como por la ferroviaria. Para lograrlo fue necesario adaptar infraestructura y formas de operación: conectar redes exige compatibilidad, además de unir líneas en un mapa.', 'Comprender que la conexión física necesita compatibilidad técnica.', 'Network Rail, inauguración del tranvía-tren', 'https://www.networkrailmediacentre.co.uk/news/uks-first-tram-train-debuts-in-south-yorkshire', 'Un tranvía-tren continúa su recorrido desde una vía tranviaria urbana hacia un corredor ferroviario.'],
  ],
  [
    ['pavimento-tactil', 'El piso también da información', 'En estaciones del metro de Londres, el pavimento con relieve ayuda a personas ciegas o con baja visión a detectar zonas importantes del andén. Sus patrones pueden percibirse con los pies o con un bastón. La accesibilidad también consiste en dar información que no dependa de leer un cartel.', 'Diseñar información que pueda percibirse de distintas maneras.', 'TfL, Haringey station upgrades unveiled', 'https://tfl.gov.uk/info-for/media/press-releases/2006/may/haringey-station-upgrades-unveiled', 'Una persona detecta con su bastón el pavimento táctil que advierte sobre la cercanía del borde del andén.'],
    ['avisos-audiovisuales', 'Un aviso puede verse y oírse', 'Los trenes más nuevos del metro de Londres ofrecen avisos tanto audibles como visibles a bordo. Presentar la información de dos maneras ayuda a que más personas puedan seguir el viaje. Una red accesible necesita comunicar destinos y paradas con claridad, además de permitir el acceso físico al vehículo.', 'Combinar información visual y sonora para orientar el viaje.', 'TfL, Plan an accessible journey', 'https://tfl.gov.uk/transport-accessibility/plan-an-accessible-journey', 'Pantalla y altavoz de un vagón comunican la misma próxima parada de una red ficticia.'],
  ],
  [
    ['polvo-subterraneo', 'Un metro eléctrico también produce polvo', 'En el metro de Londres, el polvo incluye partículas metálicas producidas por el desgaste de ruedas, rieles y frenos. TfL mide sus niveles y realiza limpiezas específicas en las zonas más afectadas. Usar electricidad no elimina la necesidad de cuidar el aire dentro de estaciones y túneles.', 'Incluir medición y limpieza en el cuidado ambiental del metro.', 'TfL, Improving air quality on the Tube', 'https://tfl.gov.uk/corporate/about-tfl/improving-air-quality-on-the-tube', 'El desgaste de ruedas y rieles genera partículas en un túnel de metro; equipos las miden y retiran.'],
    ['ruido-riel', 'Las vías también hacen ruido', 'El contacto entre ruedas metálicas y rieles produce vibraciones que pueden llegar a edificios cercanos. En Londres, el mantenimiento incluye alisar irregularidades de los rieles y reemplazar piezas desgastadas para reducir ruido y vibración. La calidad ambiental de una red también depende de cómo se cuidan sus vías.', 'Incluir ruido y mantenimiento en la evaluación ambiental.', 'TfL, Reducing noise & vibration', 'https://tfl.gov.uk/corporate/about-tfl/reducing-noise-and-vibration', 'Comparación de una rueda sobre un riel irregular y uno alisado, con menor vibración en el segundo.'],
  ],
  [
    ['codigos-estaciones', 'Una letra y un número orientan', 'Tokyo Metro identifica estaciones mediante una letra de línea y un número, además de sus nombres. Los códigos aparecen dentro de círculos del color de cada línea. Este sistema ayuda a contar las estaciones restantes y reconocer el sentido del viaje, incluso cuando el nombre de una parada resulta desconocido.', 'Combinar nombres, códigos y colores para orientarse.', 'Tokyo Metro, explicación de números de estación', 'https://www.tokyometro.jp/en/subwaymap/index.html', 'Línea ficticia con estaciones X01, X02 y X03, nombres y flecha de dirección.'],
    ['local-expreso', 'Pasar no siempre significa parar', 'En Nueva York existen servicios locales y expresos. En los tramos preparados para ese funcionamiento, los locales se detienen en todas las estaciones y los expresos solo en las paradas expresas. Una vía que pasa por una estación no garantiza que todos sus trenes permitan subir o bajar allí.', 'Comparar patrones de parada y destinos atendidos.', 'MTA, estudio Rockaway Beach Branch', 'https://www.mta.info/document/10941', 'Un servicio local se detiene en cinco estaciones y uno expreso solo en tres, en una red de ejemplo.'],
  ],
  [
    ['led-estacion-2025', 'Seis mil luces para ahorrar', 'En febrero de 2025, Londres anunció la instalación de 6.000 luces LED en la estación King’s Cross St Pancras. Estas lámparas consumen menos electricidad y duran más que la iluminación fluorescente anterior. Ahorrar energía en un metro también incluye sus estaciones, no solamente los motores de los trenes.', 'Buscar eficiencia en edificios e instalaciones de la red.', 'TfL, comunicado de febrero de 2025', 'https://tfl.gov.uk/info-for/media/press-releases/2025/february/6-000-lights-at-king-s-cross-st-pancras-converted-to-leds-providing-brighter-and-greener-journeys-for-passengers', 'Estación con luminarias LED y una anotación sobre 6.000 luces instaladas en 2025.'],
    ['calor-tunel-bunhill', 'El calor del túnel puede servir', 'En Islington, Londres, el sistema Bunhill aprovecha aire caliente extraído de túneles de la línea Northern. Una bomba de calor utiliza ese calor para calentar agua que circula hacia edificios del barrio. Así, parte de la energía que sale del metro puede tener otro uso fuera de sus estaciones.', 'Reconocer oportunidades de aprovechar calor residual.', 'Islington Council, Bunhill Heat and Power', 'https://www.islington.gov.uk/environment-and-energy/energy/bunhill-heat-network', 'El aire caliente de un túnel llega a una bomba de calor que calienta agua distribuida a edificios cercanos.'],
  ],
  [
    ['riel-blanco-calor', 'Rieles blancos contra el calor', 'En un documento de adaptación climática, TfL incluye pintar rieles de blanco para reflejar calor. El acero se dilata con temperaturas altas y puede deformarse. Para un metro con tramos al aire libre, estudiar el calor ayuda a decidir dónde reforzar controles y cómo proteger la continuidad del servicio.', 'Estudiar riesgos térmicos de tramos en superficie.', 'TfL, Climate Change and Planning for Unpredictable Weather Events', 'https://content.tfl.gov.uk/sshrp-20170321-item09-climate-change-and-planning.pdf', 'Esquema de una medida de adaptación: parte lateral de un riel exterior pintada de blanco para reflejar calor.'],
    ['hojas-piccadilly-2025', 'Hojas pequeñas, demoras reales', 'Un informe de TfL de febrero de 2025 describe cómo la caída de hojas dañó ruedas en los tramos al aire libre de la línea Piccadilly. Hubo menos trenes disponibles y cierres parciales. Una alteración pequeña en la vía puede terminar afectando la frecuencia de todo un servicio.', 'Relacionar vía, disponibilidad de trenes y frecuencia.', 'TfL, Commissioner’s report, febrero de 2025', 'https://content.tfl.gov.uk/tfl-commissioners-report-february-2025-acc.pdf', 'Secuencia de hojas en la vía, ruedas dañadas y menos trenes disponibles para prestar servicio.'],
  ],
  [
    ['tarifa-integrada', 'La tarifa también conecta el metro', 'En Santiago, buses, Metro y Tren Nos comparten una tarifa integrada con reglas de tiempo y transbordo. Esto permite combinar modos dentro de un mismo viaje. Al pensar una futura red de metro para Uruguay, también conviene estudiar cómo se pagarían y conectarían sus viajes con otros servicios.', 'Evaluar conexiones considerando tiempo y costo del pasajero.', 'Red Movilidad, Conoce las tarifas', 'https://www.red.cl/tarifas-y-recargas/conoce-las-tarifas/', 'Esquema de red ficticia con conexiones de metro, reloj y tarjeta de viaje, sin precios.'],
    ['datos-y-frecuencia', 'De los datos a la frecuencia', 'Montevideo combina datos de GPS de ómnibus y registros de pago para estimar viajes. Esa experiencia muestra el valor de estudiar la demanda antes de proponer una red. En una simulación de metro para Uruguay, los datos ayudan a comparar frecuencias, sin confundir una estimación con pasajeros futuros asegurados.', 'Transformar datos de demanda en hipótesis de servicio.', 'Intendencia de Montevideo, Analítica de datos', 'https://montevideo.gub.uy/areas-tematicas/servicios-digitales/desarrollo-sostenible-e-inteligente/analitica-de-datos', 'Datos de viajes alimentan una simulación que compara frecuencias y ocupación de estaciones de metro.'],
  ],
];

ampliacionGeneral.forEach((pareja, i) => banco[i].push(...pareja));

// Variantes E/F de Logística: ejemplos de aula, sin atribuir funciones nuevas al juego.
const ampliacionLogistica = [
  [
    ["logistica-01-e", "Del mapa al grafo", "En un ejercicio de ingeniería de software del MIT, el metro de Boston sirve para aprender grafos: estaciones y conexiones se convierten en una red que una computadora puede recorrer. Quien estudia Logística puede aplicar esa mirada a un plano ferroviario para reconocer sectores aislados y rutas posibles.", "Representar estaciones como nodos y conexiones como enlaces", "MIT OpenCourseWare, 6.170 Laboratory in Software Engineering, Problem Set 4 (2005), problema 4, pp. 9–11 del PDF", "https://ocw.mit.edu/courses/6-170-laboratory-in-software-engineering-fall-2005/622329e7756955af70101639ecadeaab_ps4.pdf", "Un plano de metro se simplifica en nodos y enlaces, conservando una estación aislada.", "logistica-01-e"],
    ["logistica-01-f", "Un origen necesita un destino", "La MTA publica estimaciones de viajes entre estaciones de origen y destino, organizadas por horario. Saber cuántas personas entran en una estación no revela adónde van. Como ejercicio de Logística, dibujá tres viajes hipotéticos sobre tu red: ¿las líneas unen ambos extremos o dejan conexiones sin resolver?", "Analizar pares de estaciones, además de contar entradas", "MTA / Estado de Nueva York, Subway Origin-Destination Ridership Estimate: 2024, descripción del conjunto de datos", "https://data.ny.gov/Transportation/MTA-Subway-Origin-Destination-Ridership-Estimate-2/jsu2-fbtj", "Tres viajes hipotéticos muestran qué orígenes y destinos logra conectar una red de metro.", "logistica-01-f"],
  ],
  [
    ["logistica-02-e", "Cruzar no es combinar", "Los modelos de transporte representan los transbordos mediante enlaces específicos entre servicios. Dos líneas que se cruzan en un dibujo no garantizan intercambio. Para estudiantes de Logística, revisar una red de metro implica señalar dónde sería posible cambiar de línea y distinguir esos puntos de los simples cruces del trazado.", "Distinguir un cruce geométrico de una conexión de transporte", "Department for Transport, TAG M3.2 Public Transport Assignment Modelling (2024), §§6.2.8–6.2.11", "https://assets.publishing.service.gov.uk/media/666af32effd07973a043d110/tag-unit-m3.2-public-transport-assignment-modelling.pdf", "Un cruce sin estación se compara con una estación que permite cambiar entre dos líneas.", "logistica-02-e"],
    ["logistica-02-f", "Combinar también lleva tiempo", "Una combinación puede incluir caminatas, cambios de nivel y espera del siguiente tren. La planificación de redes estudia esos componentes por separado. En un ejercicio de Logística, compará dos itinerarios de metro con igual cantidad de estaciones: el que exige más transbordos no necesariamente ofrece la misma experiencia de viaje.", "Descomponer el transbordo en sus partes", "MIT OpenCourseWare, Public Transportation Systems, Lecture 15: Networks and Route Structure (2017), pp. 2 y 6 del PDF", "https://ocw.mit.edu/courses/1-258j-public-transportation-systems-spring-2017/3a9389405af95c3e4a02985c5262c358_MIT1_258JS17_lec15.pdf", "Caminar, cambiar de nivel y esperar son partes de un transbordo entre trenes de metro.", "logistica-02-f"],
  ],
  [
    ["logistica-03-e", "Un atajo alrededor del centro", "La Circle Line de Singapur enlaza otras líneas y permite evitar estaciones centrales muy concurridas, como City Hall y Raffles Place. Para estudiar Logística, probá en un plano de metro una conexión transversal entre barrios: puede crear itinerarios que antes obligaban a pasar por el centro de la red.", "Evaluar conexiones transversales, además de recorridos hacia el centro", "Land Transport Authority, Circle Line, apartados Going Places Faster y Design and Architecture", "https://www.lta.gov.sg/content/ltagov/en/getting_around/public_transport/rail_network/circle_line.html", "Una conexión transversal une dos barrios sin obligar a viajar por la estación central.", "logistica-03-e"],
    ["logistica-03-f", "El recorrido directo tiene valor", "Entre los principios de diseño de redes del MIT aparece evitar recorridos innecesariamente sinuosos y facilitar conexiones. En una simulación de metro, estudiantes de Logística pueden comparar una línea que serpentea para alcanzar muchos lugares con dos líneas conectadas. El desafío es explicar qué cobertura se gana y qué rodeos aparecen.", "Comparar cobertura territorial y rodeos del trazado", "MIT OpenCourseWare, Public Transportation Systems, Lecture 15: Networks and Route Structure (2017), pp. 2 y 6 del PDF", "https://ocw.mit.edu/courses/1-258j-public-transportation-systems-spring-2017/3a9389405af95c3e4a02985c5262c358_MIT1_258JS17_lec15.pdf", "Dos diseños de metro conectan los mismos lugares mediante una línea sinuosa o dos líneas con intercambio.", "logistica-03-f"],
  ],
  [
    ["logistica-04-e", "La distancia entre estaciones importa", "Ubicar estaciones más cerca puede acortar el acceso a pie, pero suma detenciones al recorrido. Los modelos de planificación estudian ese equilibrio entre acceso, tiempo a bordo y operación. Para estudiantes de Logística, mover estaciones en un plano de metro permite discutir qué barrios se acercan al servicio y qué decisiones requieren más datos.", "Equilibrar separación de estaciones y acceso al servicio", "MIT OpenCourseWare, Public Transportation Systems, Lecture 11: Macro Design Models for a Single Route (2017), p. 3 del PDF", "https://ocw.mit.edu/courses/1-258j-public-transportation-systems-spring-2017/0f318ed94f7099b98e3ee29630ec11f9_MIT1_258JS17_lec11.pdf", "Una misma línea con estaciones separadas o cercanas muestra el equilibrio entre caminar y detenerse.", "logistica-04-e"],
    ["logistica-04-f", "Un destino se cuenta una vez", "El modelo británico de conectividad evita volver a contabilizar un destino ya alcanzado. Esa idea sirve para analizar cobertura de metro: dos estaciones cercanas pueden atender el mismo hospital. Como ejercicio de Logística, compará destinos distintos cubiertos antes y después de mover una estación, sin confundir más paradas con más lugares atendidos.", "Medir cobertura adicional sin duplicar destinos", "Department for Transport, Transport connectivity metric, apartados The model y Factors affecting node values", "https://www.gov.uk/government/publications/transport-connectivity-metric/transport-connectivity-metric", "Dos estaciones atienden el mismo hospital; mover una permite incorporar una biblioteca sin contar dos veces el hospital.", "logistica-04-f"],
  ],
  [
    ["logistica-05-e", "La flota también debe volver", "Para sostener un servicio importa el ciclo completo del tren: ida, vuelta y tiempos en las terminales. En un ejemplo de aula, un ciclo de sesenta minutos con salidas cada diez requiere seis trenes en circulación. Estudiantes de Logística pueden calcular qué ocurre si alargan la línea, manteniendo las mismas salidas.", "Relacionar duración del ciclo, intervalo y flota necesaria", "MIT OpenCourseWare, Public Transportation Systems, Lecture 12: Frequency Determination (2017), p. 2 del PDF", "https://ocw.mit.edu/courses/1-258j-public-transportation-systems-spring-2017/dcc9ef83281e06ee934b290488621f90_MIT1_258JS17_lec12.pdf", "En un ejemplo ideal, seis trenes sostienen salidas cada diez minutos cuando cada ciclo dura una hora.", "logistica-05-e"],
    ["logistica-05-f", "El promedio puede engañar", "En servicios frecuentes, la espera depende tanto del intervalo medio como de su regularidad. Dos metros pueden ofrecer igual cantidad de trenes por hora y dejar huecos muy distintos entre llegadas. En Logística, comparar secuencias de horarios hipotéticos ayuda a explicar por qué contar trenes no alcanza para evaluar la calidad del servicio.", "Distinguir cantidad de trenes y regularidad de las llegadas", "MIT OpenCourseWare, Public Transportation Systems, Lecture 20: Transit Service Reliability (2017), p. 2 del PDF", "https://ocw.mit.edu/courses/1-258j-public-transportation-systems-spring-2017/3780d832f90b2d2cd2c9b772924a32c3_MIT1_258JS17_lec20.pdf", "Dos secuencias con la misma cantidad de trenes muestran intervalos uniformes o un hueco largo entre llegadas.", "logistica-05-f"],
  ],
  [
    ["logistica-06-e", "Mirar el tramo más cargado", "La planificación de frecuencias considera las cargas máximas, que pueden cambiar según la hora. Un promedio de toda la línea puede esconder un tramo exigido. Para aprender Logística, asigná en papel viajes hipotéticos entre estaciones de metro y contá cuántos atraviesan cada segmento: localizar ese tramo ayuda a formular mejores preguntas.", "Distinguir carga media y carga máxima por segmento", "MIT OpenCourseWare, Public Transportation Systems, Lecture 12: Frequency Determination (2017), p. 2 del PDF", "https://ocw.mit.edu/courses/1-258j-public-transportation-systems-spring-2017/dcc9ef83281e06ee934b290488621f90_MIT1_258JS17_lec12.pdf", "Tres viajes ficticios coinciden en el tramo B–C, que concentra más recorridos que los extremos.", "logistica-06-e"],
    ["logistica-06-f", "Una estación junto al estadio", "La estación Stadium de Singapur fue diseñada para recibir aumentos de público durante eventos deportivos y espectáculos. Un destino no genera siempre la misma actividad. En una práctica de Logística, imaginá dos situaciones para tu red de metro: un día habitual y la salida de un evento. ¿Qué conexiones convendría revisar primero?", "Examinar demanda concentrada por lugar y momento", "Land Transport Authority, Circle Line, apartados Going Places Faster y Design and Architecture", "https://www.lta.gov.sg/content/ltagov/en/getting_around/public_transport/rail_network/circle_line.html", "Una estación próxima a un estadio recibe actividad distinta en un día habitual y al terminar un evento.", "logistica-06-f"],
  ],
  [
    ["logistica-07-e", "No toda la flota está disponible", "Los planes de flota ferroviaria contemplan vehículos fuera de servicio por mantenimiento y reservas para sostener la operación. La cantidad comprada no equivale a la cantidad disponible cada día. Como ejercicio de Logística, separá los trenes de un metro hipotético entre circulación, mantenimiento y reserva antes de proponer una frecuencia.", "Distinguir flota total, disponible y asignada al servicio", "Federal Transit Administration, Circular C 5010.1F (1 de noviembre de 2024), pp. IV-39–IV-40", "https://www.transit.dot.gov/sites/fta.dot.gov/files/2024-10/C5010.1F-Circular-11-01-2024_0.pdf", "La flota total de un metro se reparte entre trenes en servicio, mantenimiento y reserva.", "logistica-07-e"],
    ["logistica-07-f", "Construir y operar son cuentas distintas", "La planificación distingue inversión inicial, como vías y trenes, de gastos de operación, como personal y materiales. En un ejercicio de Logística, se pueden comparar recursos de construcción y funcionamiento de dos diseños de metro, sin tratar la inversión inicial como si cubriera también la operación.", "Diferenciar inversión inicial y gasto operativo", "MIT OpenCourseWare, Public Transportation Systems, Lecture 7: Cost Estimation (2017), p. 1 del PDF", "https://ocw.mit.edu/courses/1-258j-public-transportation-systems-spring-2017/354e8a5bb66fa39450b92d29066e8bf6_MIT1_258JS17_lec07.pdf", "La construcción de una red y su operación cotidiana requieren tipos distintos de recursos.", "logistica-07-f"],
  ],
  [
    ["logistica-08-e", "¿A qué lugares permite llegar?", "El indicador británico de conectividad considera los destinos alcanzables y el tiempo necesario para llegar. Tener una estación cerca es solo parte del análisis. En Logística, podés revisar sobre un plano de metro si viviendas, centros de estudio y servicios quedan conectados, distinguiendo cobertura cercana de posibilidades de viaje por la red.", "Distinguir proximidad a una estación y acceso a destinos", "Department for Transport, Transport connectivity metric, apartados The model y Factors affecting node values", "https://www.gov.uk/government/publications/transport-connectivity-metric/transport-connectivity-metric", "Una estación cercana a una vivienda permite alcanzar algunos destinos, mientras otro queda aislado de la red.", "logistica-08-e"],
    ["logistica-08-f", "El beneficio no llega igual a todos", "La evaluación de transporte del Reino Unido analiza cómo los beneficios y problemas afectan a distintos grupos sociales. Para estudiantes de Logística, una red de metro puede estudiarse barrio por barrio: compará qué zonas ganan destinos y cuáles siguen aisladas. Un buen resultado total puede ocultar diferencias importantes dentro del mismo mapa.", "Revisar la distribución territorial de las mejoras", "Department for Transport, TAG A4.2 Distributional Impact Appraisal, presentación de la guía (actualización 2024)", "https://www.gov.uk/government/publications/tag-unit-a4-2-distributional-impact-appraisal", "La misma ampliación de metro conecta nuevos destinos para un barrio, mientras otro sigue aislado.", "logistica-08-f"],
  ],
  [
    ["logistica-09-e", "Una segunda ruta puede ayudar", "La autoridad de transporte de Singapur relaciona las rutas alternativas con una red más resistente a interrupciones. En un ejercicio de Logística, tapá una estación en un dibujo de tu metro y buscá otro camino entre los extremos. Si no existe, identificaste una dependencia que merece atención al planificar conexiones.", "Detectar dependencias y caminos alternativos", "Land Transport Authority, Upcoming Projects, introducción sobre conectividad, confiabilidad y rutas alternativas", "https://www.lta.gov.sg/content/ltagov/en/upcoming_projects.html", "Una estación cerrada corta una ruta, pero una segunda conexión permite seguir uniendo sus extremos.", "logistica-09-e"],
    ["logistica-09-f", "Las obras también necesitan un plan", "Para trabajos de marzo de 2026, Singapur anunció cambios de servicio entre Tanah Merah y Expo, acompañados por trenes lanzadera y ómnibus de conexión. La operación del metro debía reorganizarse mientras avanzaban las obras. En Logística, estudiar un cierre hipotético ayuda a distinguir el trazado permanente del servicio que puede ofrecerse temporalmente.", "Planificar continuidad durante cierres de infraestructura", "Land Transport Authority, East–West Line Train Service Adjustments, folleto para el 14–17 de marzo de 2026", "https://www.lta.gov.sg/content/dam/ltagov/Interactive_map/pdf/EWL%20Train%20Service%20Adjustments%20Brochure%20-%2014%20to%2017%20Mar.pdf", "Un tramo de metro en obras se sustituye temporalmente por un ómnibus mientras otro tramo mantiene un tren lanzadera.", "logistica-09-f"],
  ],
  [
    ["logistica-10-e", "Probá también otro supuesto", "La guía británica de modelos de transporte pide documentar supuestos y comprobar cómo cambian los resultados al variar las condiciones. En Logística, podés comparar dos diseños de metro con el mismo objetivo de cobertura y registrar sus recursos. Después, cambiá una condición del ejercicio y explicá si tu elección sigue teniendo sentido.", "Defender una decisión y comprobar su sensibilidad", "Department for Transport, TAG M1.1 Principles of Modelling and Forecasting (2024), §6.2 y cuadro 1", "https://assets.publishing.service.gov.uk/media/666af22a50dca4553304f333/tag-unit-m1.1-principles-modelling-forecasting.pdf", "Dos diseños de metro se comparan con el mismo objetivo y vuelven a revisarse cuando cambia un supuesto.", "logistica-10-e"],
    ["logistica-10-f", "Una tesis miró el viaje completo", "En 2009, David Uniman estudió la confiabilidad del Underground londinense usando datos de tarjetas de viaje. Su tesis de Transporte y Planificación Urbana analizó variaciones entre orígenes y destinos. Es un aporte universitario documentado: estudiantes de Logística pueden inspirarse en su pregunta central, cómo medir el servicio desde la experiencia de quien viaja.", "Formular investigaciones centradas en la experiencia del pasajero", "MIT DSpace, David Louis Uniman, Service reliability measurement framework using smart card data: application to the London Underground (2009), resumen y titulación", "https://dspace.mit.edu/entities/publication/4d7ae0f7-3472-4458-9156-576bbfd918dc", "Una investigación universitaria compara la variación de los viajes entre dos estaciones del metro.", "logistica-10-f"],
  ],
];

ampliacionLogistica.forEach((pareja, i) => banco[i].push(...pareja));
const ampliacionSetenta = [
  ["metro-ciudad", "El metro también modifica la ciudad", "Una estación no solamente responde a la demanda de transporte existente: también puede crear nueva demanda. Al mejorar la accesibilidad de una zona, puede favorecer la aparición de viviendas, comercios y oficinas alrededor de ella. Por este motivo, transporte y planificación urbana están estrechamente relacionados y las decisiones sobre dónde construir una línea pueden influir en el crecimiento futuro de una ciudad.", "Relacionar accesibilidad y desarrollo urbano.", "TransLink, Transit-Oriented Communities", "https://www.translink.ca/plans-and-projects/strategies-plans-and-guidelines/transit-oriented-communities", "Una estación de metro conecta un barrio con viviendas, comercios y oficinas.", "1-7"],
  ["metro-vapor-1863", "El primer metro del mundo", "El primer ferrocarril subterráneo del mundo comenzó a funcionar en Londres en 1863. Curiosamente, el primer metro de Londres todavía no usaba trenes eléctricos: las primeras locomotoras funcionaban a vapor, por lo que controlar el humo y la ventilación dentro de los túneles era uno de los grandes problemas del sistema. La electrificación posterior hizo posible desarrollar redes subterráneas mucho más extensas.", "Distinguir el metro a vapor de su electrificación posterior.", "Transport for London, Tube 160 Heritage Leaflet", "https://foi.tfl.gov.uk/FOI-0773-2324/TUBE160%20Heritage%20Leaflet.pdf", "Un tren a vapor circula por un túnel histórico con ventilación hacia la superficie.", "2-7"],
  ["metro-red-radial", "El problema de las redes radiales", "Muchas redes históricas crecieron conectando los barrios periféricos con el centro de la ciudad. Este diseño funciona muy bien cuando la mayoría de los viajes tienen como destino el centro, pero puede hacer incómodo viajar entre dos barrios periféricos: a veces el pasajero debe acercarse al centro para después volver a alejarse. Las líneas circulares y transversales ayudan a evitar este problema.", "Comparar recorridos radiales con conexiones transversales.", "Société des Grands Projets, Grand Paris Express", "https://www.grandparisexpress.fr/gpe-essentiel", "Una red radial obliga a pasar por el centro; un arco transversal une dos barrios exteriores.", "3-7"],
  ["metro-distancia-estaciones", "Más estaciones no siempre significa mejor servicio", "Colocar muchas estaciones aumenta la cantidad de lugares a los que llega una línea, pero también hace que los trenes tengan que detenerse, frenar y acelerar con mayor frecuencia. Separarlas demasiado produce el problema contrario: los viajes son más rápidos, pero menos personas tienen una estación cerca. Elegir la distancia entre estaciones es, por tanto, un equilibrio entre cobertura y velocidad.", "Equilibrar cobertura y velocidad al ubicar estaciones.", "TransLink, Transit-Oriented Communities", "https://www.translink.ca/plans-and-projects/strategies-plans-and-guidelines/transit-oriented-communities", "Dos esquemas comparan estaciones cercanas y separadas con áreas de cobertura.", "4-7"],
  ["metro-grafo", "Una red de metro también es un problema matemático", "Para estudiar una red de metro no es necesario dibujar calles, edificios o incluso las distancias reales entre estaciones. Podemos imaginarla simplemente como puntos unidos por líneas: cada punto representa una estación y cada unión indica que es posible viajar directamente entre ambas. Esta representación se conoce como grafo y permite responder preguntas como cuál es el camino más corto entre dos estaciones, qué recorrido requiere menos transbordos o qué estaciones son fundamentales para mantener conectada la red. La misma idea se utiliza para estudiar carreteras, redes informáticas e incluso relaciones entre personas.", "Modelar estaciones y conexiones como un grafo.", "Princeton University, Algorithms, Undirected Graphs", "https://algs4.cs.princeton.edu/41graph/index.php", "Un mapa esquemático de metro se transforma en nodos y enlaces de un grafo.", "5-7"],
  ["metro-bajo-tierra", "¿Por qué construir bajo tierra?", "Construir túneles es mucho más caro y complejo que instalar vías en la superficie, pero tiene una gran ventaja en ciudades densamente construidas: permite crear nuevas rutas sin ocupar calles ni dividir barrios con vías ferroviarias. Además, al circular en una infraestructura completamente separada, los trenes no interfieren con automóviles, peatones o semáforos. Por eso muchos sistemas combinan tramos subterráneos en las zonas más congestionadas con tramos elevados o en superficie donde existe más espacio.", "Comparar tramos subterráneos y superficiales según el espacio urbano.", "Metrolinx, Ontario Line and other world-class transit systems", "https://www.metrolinx.com/en/discover/how-the-ontario-line-lines-up-other-world-class-transit-systems", "Corte de ciudad con peatones y tránsito en superficie, y un tren en un túnel separado debajo.", "6-7"],
  ["metro-transbordos", "Los transbordos conectan la red", "Los transbordos permiten pasar de una línea a otra y hacen posible llegar a lugares que una sola línea no podría cubrir. Su ubicación es especialmente importante, un transbordo bien situado puede evitar grandes rodeos, mientras que una red con pocas conexiones entre líneas puede obligar a los pasajeros a realizar recorridos mucho más largos, caminar más de lo deseado o incluso combinar varios sistemas de transporte diferentes. Por eso, al diseñar una red, no sólo importa por dónde pasa cada línea, sino también dónde se conectan entre sí.", "Ubicar conexiones entre líneas para evitar rodeos.", "Transport for London, West London Orbital", "https://haveyoursay.tfl.gov.uk/west-london-orbital?tool=news_feed", "Dos líneas de metro se conectan en una estación de intercambio, con recorridos antes y después.", "7-7"],
  ["metro-nueva-linea", "Una línea nueva puede mejorar líneas antiguas", "El beneficio de construir una línea no se limita a las estaciones nuevas que incorpora. Si cruza varias líneas existentes y crea nuevos transbordos, también puede reducir los recorridos necesarios entre estaciones que ya formaban parte de la red. Por eso, al planificar una ampliación, importa tanto qué lugares atraviesa, como las conexiones que genera.", "Evaluar conexiones nuevas entre estaciones existentes.", "Société des Grands Projets, Benefit of the metro for Île-de-France", "https://www.grandparisexpress.fr/benefit-metro-ile-de-france", "Una línea nueva enlaza dos líneas antiguas mediante estaciones de transbordo.", "8-7"],
  ["metro-redundancia", "Construir redundancia tiene un precio", "Tener varios caminos posibles entre dos zonas hace que una red sea más resistente: si un tramo queda fuera de servicio, los pasajeros pueden utilizar otra ruta. Sin embargo, construir infraestructura redundante también cuesta dinero. Parte del diseño de una red consiste en decidir dónde merece la pena disponer de alternativas y dónde una única conexión resulta suficiente.", "Comparar resiliencia de rutas alternativas con su costo.", "Federal Highway Administration, Transportation Network Redundancy", "https://ops.fhwa.dot.gov/publications/fhwahop08015/lit6_8.htm", "Un tramo bloqueado contrasta una red con ruta alternativa y otra sin desvío.", "9-7"],
  ["metro-estacion-critica", "Una estación puede ser importante aunque no sea la más utilizada", "Algunas estaciones tienen un papel crítico simplemente por su posición dentro de la red. Si queda fuera de servicio una estación que constituye el único enlace entre dos sectores, esto podría obligar a realizar enormes desvíos o incluso separar la red en dos partes. Analizar estos puntos vulnerables permite diseñar sistemas más resistentes ante averías o interrupciones.", "Identificar estaciones cuyo enlace sostiene la conectividad de la red.", "Princeton University, Algorithms, Undirected Graphs", "https://algs4.cs.princeton.edu/41graph/index.php", "Una estación puente es el único enlace entre dos sectores; al interrumpirse el paso, los sectores quedan separados.", "10-7"],
];
ampliacionSetenta.forEach((fila, i) => banco[i].push(fila));



export const tarjetasEducativas = Object.freeze(banco.map((pareja, i) => Object.freeze(pareja.map((fila, j) => Object.freeze({
  id: fila[7] ?? `${i + 1}-${j + 1}`,
  imagen: `/assets/educacion/${fila[0]}.svg`,
  titulo: fila[1], texto: fila[2], aprendizaje: fila[3], fuente: fila[4], url: fila[5], descripcionImagen: fila[6],
})))));

const ultimasEnMemoria = new Map();
const usadasEnMemoria = new Map();
const prefijo = 'metronet:educacion:ultimo:';
const prefijoUsadas = 'metronet:educacion:usadas:';
const publicadas = new Map();
const ultimaPublicadaEnMemoria = new Map();
const usadasPublicadasEnMemoria = new Map();

export function registrarTarjetasPublicadas(numero, contenido, idUsuario, idIntento = null) {
  if (!Number.isInteger(numero) || !Array.isArray(contenido?.tarjetas) || ![6, 7].includes(contenido.tarjetas.length)) return;
  const ids = contenido.tarjetas.map(t => t.id);
  if (new Set(ids).size !== ids.length || ids.some(id => typeof id !== 'string' || !id)) return;
  publicadas.set(numero, { tarjetas: contenido.tarjetas, version: contenido.version,
    usuario: idUsuario ?? 'sesion', idIntento });
}

export function limpiarTarjetasPublicadas(numero) {
  publicadas.delete(numero);
}

export function tarjetasDisponibles(numero) {
  return publicadas.get(numero)?.tarjetas ?? tarjetasEducativas[numero - 1] ?? [];
}

function estadoPublicado(numero) {
  const publicacion = publicadas.get(numero);
  if (!publicacion) return null;
  const clave = `${publicacion.usuario}:${numero}:${publicacion.version}`;
  const ultimoKey = `metronet:educacion:ultimo-id:${clave}`;
  const usadasKey = `metronet:educacion:usadas-id:${clave}`;
  let ultimo = ultimaPublicadaEnMemoria.get(clave) ?? null;
  let usadas = usadasPublicadasEnMemoria.get(clave) ?? null;
  const ids = publicacion.tarjetas.map(t => t.id);
  try {
    if (ultimo === null) ultimo = localStorage.getItem(ultimoKey);
    if (usadas === null) usadas = JSON.parse(localStorage.getItem(usadasKey));
    const migradaKey = `metronet:educacion:migrada:${clave}`;
    if (publicacion.version === 1 && !localStorage.getItem(migradaKey)) {
      const indiceAnterior = Number(localStorage.getItem(`${prefijo}${numero}`));
      const indices = JSON.parse(localStorage.getItem(`${prefijoUsadas}${numero}`));
      if (localStorage.getItem(`${prefijo}${numero}`) !== null && Number.isInteger(indiceAnterior))
        ultimo = ids[indiceAnterior] ?? null;
      if (Array.isArray(indices) && indices.every(i => Number.isInteger(i) && ids[i]))
        usadas = [...new Set(indices.map(i => ids[i]))];
      localStorage.setItem(migradaKey, '1');
    }
  } catch { /* El almacenamiento puede estar deshabilitado o contener datos legados inválidos. */ }
  if (!ids.includes(ultimo)) ultimo = null;
  if (!Array.isArray(usadas) || usadas.some(id => !ids.includes(id)) || new Set(usadas).size !== usadas.length) usadas = [];
  return { publicacion, clave, ultimoKey, usadasKey, ultimo, usadas };
}

function seleccionarPublicada(numero) {
  const estado = estadoPublicado(numero);
  if (!estado) return null;
  const tarjetas = estado.publicacion.tarjetas;
  const usadas = estado.usadas.length === tarjetas.length ? [] : estado.usadas;
  let candidatas = tarjetas.filter(t => !usadas.includes(t.id));
  if (!usadas.length && candidatas.length > 1) candidatas = candidatas.filter(t => t.id !== estado.ultimo);
  const tarjeta = candidatas[Math.floor(Math.random() * candidatas.length)];
  usadasPublicadasEnMemoria.set(estado.clave, [...usadas, tarjeta.id]);
  ultimaPublicadaEnMemoria.set(estado.clave, tarjeta.id);
  try {
    localStorage.setItem(estado.ultimoKey, tarjeta.id);
    localStorage.setItem(estado.usadasKey, JSON.stringify([...usadas, tarjeta.id]));
  } catch { /* La rotación sigue en memoria. */ }
  return tarjeta;
}

function ultima(numero) {
  if (ultimasEnMemoria.has(numero)) return ultimasEnMemoria.get(numero);
  try {
    const guardada = localStorage.getItem(`${prefijo}${numero}`);
    const indice = Number(guardada);
    if (guardada !== null && Number.isInteger(indice) && indice >= 0 && indice < (tarjetasEducativas[numero - 1]?.length ?? 0)) return indice;
  } catch { /* El almacenamiento puede estar deshabilitado. */ }
  return ultimasEnMemoria.get(numero) ?? -1;
}

export function seleccionarTarjetaEducativa(numero) {
  if (publicadas.has(numero)) return seleccionarPublicada(numero);
  const pareja = tarjetasEducativas[numero - 1];
  if (!pareja) return null;
  let usadas = usadasEnMemoria.get(numero);
  if (!usadas) {
    try {
      const guardadas = JSON.parse(localStorage.getItem(`${prefijoUsadas}${numero}`));
      if (Array.isArray(guardadas) && guardadas.every(i => Number.isInteger(i) && i >= 0 && i < pareja.length)
        && new Set(guardadas).size === guardadas.length) usadas = guardadas;
    } catch { /* Continúa con un ciclo nuevo en memoria. */ }
    usadas ??= [];
  }
  if (usadas.length === pareja.length) usadas = [];
  let candidatas = pareja.map((_, i) => i).filter(i => !usadas.includes(i));
  if (usadas.length === 0 && candidatas.length > 1) candidatas = candidatas.filter(i => i !== ultima(numero));
  const indice = candidatas[Math.floor(Math.random() * candidatas.length)];
  usadas = [...usadas, indice];
  usadasEnMemoria.set(numero, usadas);
  ultimasEnMemoria.set(numero, indice);
  try {
    localStorage.setItem(`${prefijo}${numero}`, String(indice));
    localStorage.setItem(`${prefijoUsadas}${numero}`, JSON.stringify(usadas));
  } catch { /* Continúa en memoria. */ }
  return pareja[indice];
}

export function tarjetaEducativaActual(numero) {
  const publicada = estadoPublicado(numero);
  if (publicada) return publicada.publicacion.tarjetas.find(t => t.id === publicada.ultimo)
    ?? publicada.publicacion.tarjetas[0];
  const pareja = tarjetasEducativas[numero - 1];
  if (!pareja) return null;
  return pareja[Math.max(0, ultima(numero))];
}
