ALTER TABLE simulacion
  ADD COLUMN IF NOT EXISTS estado VARCHAR(30) NOT NULL DEFAULT 'COMPLETADA';

ALTER TABLE simulacion
  ADD COLUMN IF NOT EXISTS puntaje INTEGER;

ALTER TABLE simulacion
  ADD COLUMN IF NOT EXISTS fecha_ejecucion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
