package com.metronet.backend.configuracion;

import static org.junit.jupiter.api.Assertions.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.metronet.backend.service.*;
import java.sql.DriverManager;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

/** SQL real de catálogo/progreso sobre tablas TEMP privadas de la conexión y rollback.
 * No modifica tablas ni secuencias persistentes; no sustituye una prueba HTTP de extremo a extremo. */
@EnabledIfEnvironmentVariable(named = "METRONET_TEST_POSTGRES_URL", matches = "jdbc:postgresql:.*")
class CampanaPostgresTest {
    @Test
    void catalogoIdempotenteDiezSolucionesRecargaReinicioYLogroHistoricoEnPostgres() throws Exception {
        try (var conexion = DriverManager.getConnection(System.getenv("METRONET_TEST_POSTGRES_URL"),
            System.getenv().getOrDefault("METRONET_TEST_POSTGRES_USER", "postgres"),
            System.getenv().getOrDefault("METRONET_TEST_POSTGRES_PASSWORD", ""))) {
            conexion.setAutoCommit(false);
            var jdbc = new JdbcTemplate(new SingleConnectionDataSource(conexion, true));
            try {
                jdbc.execute("CREATE TEMP TABLE usuario(id_usuario INT PRIMARY KEY, numero_campana_actual INT, campana_completada_historicamente BOOLEAN) ON COMMIT DROP");
                jdbc.execute("CREATE TEMP TABLE escenario(id_escenario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, numero INT, nombre VARCHAR, objetivo VARCHAR, dificultad VARCHAR, instrucciones VARCHAR, modo VARCHAR, progresivo BOOLEAN, reglas_exito JSONB, herramientas_habilitadas JSONB) ON COMMIT DROP");
                jdbc.execute("CREATE TEMP TABLE intento(id_intento INT PRIMARY KEY, id_usuario INT, id_escenario INT, id_diseno INT, numero_campana INT, estado VARCHAR, progreso INT, puntaje INT, fecha_finalizacion TIMESTAMP) ON COMMIT DROP");
                jdbc.execute("CREATE TEMP TABLE estacion(id_diseno INT, nombre VARCHAR, posicion_x NUMERIC(10,2), posicion_y NUMERIC(10,2), transbordo BOOLEAN) ON COMMIT DROP");
                jdbc.execute("CREATE TEMP TABLE linea(id_diseno INT, nombre VARCHAR) ON COMMIT DROP");
                jdbc.execute("CREATE TEMP TABLE tramo(id_diseno INT, nombre_linea VARCHAR, nombre_estacion_a VARCHAR, nombre_estacion_b VARCHAR) ON COMMIT DROP");
                jdbc.execute("CREATE TEMP TABLE pasa(id_diseno INT, nombre_linea VARCHAR, nombre_estacion VARCHAR) ON COMMIT DROP");
                jdbc.execute("CREATE TEMP TABLE metro(id_diseno INT, id_tren INT GENERATED BY DEFAULT AS IDENTITY, nombre_linea VARCHAR, velocidad_promedio NUMERIC(10,2), capacidad INT DEFAULT 300) ON COMMIT DROP");
                jdbc.execute("CREATE TEMP TABLE simulacion(id_intento INT, comentarios TEXT, id_simulacion INT GENERATED BY DEFAULT AS IDENTITY, puntaje INT DEFAULT 0) ON COMMIT DROP");
                jdbc.update("INSERT INTO usuario VALUES (7,1,FALSE)");
                jdbc.execute("ALTER TABLE usuario ADD COLUMN rol VARCHAR DEFAULT 'JUGADOR'");
                var inicializador = new InicializadorCatalogoEscenariosProgresivos().inicializarCatalogoEscenariosProgresivos(jdbc);
                inicializador.run(); inicializador.run();
                assertEquals(11, jdbc.queryForObject("SELECT COUNT(*) FROM escenario", Integer.class));
                var mapper = new ObjectMapper();
                var geo = new GeografiaService(mapper);
                var restricciones = new RestriccionesGeograficasService(jdbc, mapper, geo);
                var juego = new JuegoEducativoService(jdbc, mapper, new ObjetivosPuntosInteresService(mapper, geo), new CondicionesGeograficasService(jdbc, mapper, geo, restricciones));
                for (int nivel = 1; nivel <= 10; nivel++) {
                    int idEscenario = jdbc.queryForObject("SELECT id_escenario FROM escenario WHERE numero=?", Integer.class, nivel);
                    var reglas = mapper.readTree(jdbc.queryForObject("SELECT reglas_exito::text FROM escenario WHERE numero=?", String.class, nivel));
                    jdbc.update("INSERT INTO intento VALUES (?,7,?,?,1,'EN_DESARROLLO',0,NULL,NULL)", nivel, idEscenario, nivel);
                    assertEquals(nivel, juego.iniciarEscenario(7, idEscenario).idDiseno(), "Reanudar conserva diseño");
                    assertFalse(juego.evaluarEscenario(7, nivel).completado());
                    int indice = 0;
                    for (var objetivo : reglas.path("puntosInteresObjetivo")) {
                        var poi = geo.resolverPunto(objetivo.path("idPunto").asInt(), null);
                        jdbc.update("INSERT INTO estacion VALUES (?,?,?,?,TRUE)", nivel, "E" + indice++, geo.posicionX(poi), geo.posicionY(poi));
                    }
                    int cantidad = reglas.path("minimoEstaciones").asInt();
                    while (indice < cantidad) { jdbc.update("INSERT INTO estacion VALUES (?,?,?,?,TRUE)", nivel, "E" + indice, 660 + indice * 5, 460); indice++; }
                    jdbc.update("INSERT INTO linea VALUES (?,'Principal')", nivel);
                    for (int i = 0; i < cantidad; i++) {
                        jdbc.update("INSERT INTO pasa VALUES (?,'Principal',?)", nivel, "E" + i);
                        if (i > 0) jdbc.update("INSERT INTO tramo VALUES (?,'Principal',?,?)", nivel, "E" + (i - 1), "E" + i);
                    }
                    for (int i = 1; i < reglas.path("minimoLineas").asInt(); i++) {
                        String linea = "Enlace" + i;
                        String origen = "E" + (nivel == 10 ? i - 1 : 0);
                        jdbc.update("INSERT INTO linea VALUES (?,?)", nivel, linea);
                        jdbc.update("INSERT INTO pasa VALUES (?,?,?),(?,?,'E2')", nivel, linea, origen, nivel, linea);
                        jdbc.update("INSERT INTO tramo VALUES (?,?,?,'E2')", nivel, linea, origen);
                    }
                    for (int i = 0; i < reglas.path("minimoMetros").asInt(); i++) jdbc.update("INSERT INTO metro(id_diseno,nombre_linea,velocidad_promedio) VALUES (?,?,?)", nivel, i == 0 ? "Principal" : "Enlace" + i, reglas.path("puntuacion").path("velocidadObjetivoKmh").asInt(40));
                    if (reglas.path("requiereSimulacion").asBoolean()) jdbc.update("INSERT INTO simulacion(id_intento,comentarios) VALUES (?,?)", nivel, juego.marcaRedSimulada(nivel));
                    assertTrue(restricciones.observarDiseno(nivel).isEmpty(), "Territorio nivel " + nivel);
                    var resultado = juego.evaluarEscenario(7, nivel);
                    assertTrue(resultado.completado(), "Nivel " + nivel);
                    assertEquals(nivel == 10, resultado.idSiguienteEscenario() == null);
                    assertEquals(nivel, juego.obtenerResumenProgreso(7).nivelesCompletados());
                }
                // Una instancia nueva lee el mismo progreso persistido, sin estado del navegador.
                var recargado = new JuegoEducativoService(jdbc, mapper, new ObjetivosPuntosInteresService(mapper, geo), new CondicionesGeograficasService(jdbc, mapper, geo, restricciones));
                assertTrue(recargado.obtenerResumenProgreso(7).campanaCompletada());
                var puntos = new PuntuacionService(jdbc, mapper, geo);
                var ranking = puntos.ranking(7);
                assertEquals(1, ranking.tuPosicion());
                assertEquals(10, ranking.jugadores().getFirst().nivelesCompletados());
                assertTrue(ranking.puntajeTotal() > 0 && ranking.puntajeTotal() <= ranking.puntajeMaximo());
                int escenarioSeis = jdbc.queryForObject("SELECT id_escenario FROM escenario WHERE numero=6", Integer.class);
                jdbc.update("INSERT INTO intento VALUES (20,7,?,20,1,'COMPLETADO',100,50,NULL)", escenarioSeis);
                assertEquals(ranking.puntajeTotal(), puntos.ranking(7).puntajeTotal());
                var reinicio = recargado.reiniciarRecorrido(7, 1);
                assertEquals(0, reinicio.nivelesCompletados());
                assertTrue(reinicio.modoLibreDesbloqueado());
                assertEquals(11, jdbc.queryForObject("SELECT COUNT(*) FROM intento WHERE estado='COMPLETADO'", Integer.class));
                assertEquals(ranking.puntajeTotal(), puntos.ranking(7).puntajeTotal());
                jdbc.update("UPDATE usuario SET rol='ADMIN' WHERE id_usuario=7");
                assertTrue(recargado.obtenerResumenProgreso(7).escenarios().stream().allMatch(e -> e.desbloqueado()));
                assertEquals(0, puntos.ranking(7).jugadores().size());
                jdbc.update("UPDATE escenario SET objetivo='Consigna personalizada', reglas_exito=reglas_exito || '{\"maximoEstaciones\":20}'::jsonb WHERE numero=5");
                inicializador.run();
                assertEquals("Consigna personalizada", jdbc.queryForObject("SELECT objetivo FROM escenario WHERE numero=5", String.class));
                assertEquals(20, jdbc.queryForObject("SELECT (reglas_exito->>'maximoEstaciones')::int FROM escenario WHERE numero=5", Integer.class));
            } finally { conexion.rollback(); }
            assertNull(jdbc.queryForObject("SELECT to_regclass('pg_temp.escenario')::text", String.class));
        }
    }
}
