package com.metronet.backend.configuracion;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.metronet.backend.dto.ConsignaDisenoResponse;
import com.metronet.backend.entity.Usuario;
import com.metronet.backend.enums.Rol;
import com.metronet.backend.service.*;
import java.util.UUID;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;
import org.springframework.web.server.ResponseStatusException;

/** Ejecuta SQL y servicios reales sobre H2. No prueba PostgreSQL ni modifica sus datos. */
class JuegoGeograficoIntegracionTest {
    private SingleConnectionDataSource fuente;
    private JdbcTemplate jdbc;
    private JuegoEducativoService juego;
    private final ObjectMapper mapper = new ObjectMapper();
    private final GeografiaService geografia = new GeografiaService(mapper);
    private Usuario usuario;

    @BeforeEach
    void preparar() throws Exception {
        fuente = new SingleConnectionDataSource("jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE", "sa", "", true);
        jdbc = new JdbcTemplate(fuente);
        jdbc.execute("CREATE TABLE usuario(id_usuario INT PRIMARY KEY, numero_campana_actual INT, campana_completada_historicamente BOOLEAN)");
        jdbc.execute("CREATE TABLE escenario(id_escenario INT PRIMARY KEY, numero INT, nombre VARCHAR, objetivo VARCHAR, dificultad VARCHAR, instrucciones VARCHAR, modo VARCHAR, progresivo BOOLEAN, reglas_exito VARCHAR, herramientas_habilitadas VARCHAR)");
        jdbc.execute("CREATE TABLE intento(id_intento INT PRIMARY KEY, id_usuario INT, id_escenario INT, id_diseno INT, numero_campana INT, estado VARCHAR, progreso INT, puntaje INT, fecha_finalizacion TIMESTAMP)");
        jdbc.execute("CREATE TABLE estacion(id_diseno INT, nombre VARCHAR, posicion_x DECIMAL(20,12), posicion_y DECIMAL(20,12), transbordo BOOLEAN)");
        jdbc.execute("CREATE TABLE linea(id_diseno INT, nombre VARCHAR)");
        jdbc.execute("CREATE TABLE tramo(id_diseno INT, nombre_linea VARCHAR, nombre_estacion_a VARCHAR, nombre_estacion_b VARCHAR)");
        jdbc.execute("CREATE TABLE pasa(id_diseno INT, nombre_linea VARCHAR, nombre_estacion VARCHAR)");
        jdbc.execute("CREATE TABLE metro(id_diseno INT, id_tren INT GENERATED BY DEFAULT AS IDENTITY, nombre_linea VARCHAR, velocidad_promedio DECIMAL(10,2) DEFAULT 40, capacidad INT DEFAULT 300)");
        jdbc.execute("CREATE TABLE simulacion(id_intento INT, comentarios VARCHAR, id_simulacion INT GENERATED BY DEFAULT AS IDENTITY, puntaje INT DEFAULT 0)");
        jdbc.update("INSERT INTO usuario VALUES (7,1,FALSE)");
        jdbc.execute("ALTER TABLE usuario ADD COLUMN rol VARCHAR DEFAULT 'JUGADOR'");
        // Las consignas provienen del inicializador de producción, no de una copia en la prueba.
        JdbcTemplate catalogo = mock(JdbcTemplate.class);
        when(catalogo.update(anyString(), any(Object[].class))).thenAnswer(invocacion -> {
            String sql = invocacion.getArgument(0);
            Object[] argumentos = (Object[]) invocacion.getRawArguments()[1];
            if (sql.contains("INSERT INTO escenario") && argumentos.length == 8) {
                int numero = (int) argumentos[2];
                jdbc.update("INSERT INTO escenario VALUES (?,?,?,?,?,?,'NIVEL',TRUE,?,?)", numero, numero,
                    argumentos[0], argumentos[1], argumentos[3], argumentos[4], argumentos[5], argumentos[6]);
            }
            return 1;
        });
        new InicializadorCatalogoEscenariosProgresivos().inicializarCatalogoEscenariosProgresivos(catalogo).run();
        juego = new JuegoEducativoService(jdbc, mapper, new ObjetivosPuntosInteresService(mapper, geografia),
            new CondicionesGeograficasService(jdbc, mapper, geografia, new RestriccionesGeograficasService(jdbc, mapper, geografia)));
        usuario = new Usuario(); usuario.setIdUsuario(7); usuario.setRol(Rol.JUGADOR);
        for (int nivel = 1; nivel <= 4; nivel++) {
            jdbc.update("INSERT INTO intento VALUES (?,?,?, ?,1,'EN_DESARROLLO',0,NULL,NULL)", nivel, 7, nivel, nivel);
        }
    }

    @AfterEach
    void cerrar() { if (fuente != null) fuente.destroy(); }

    private void red(int diseno) {
        var palacio = geografia.resolverPunto(1, null);
        var rambla = geografia.resolverPunto(26, null);
        jdbc.update("INSERT INTO estacion VALUES (?,'A',?,?,FALSE)", diseno, geografia.posicionX(palacio), geografia.posicionY(palacio));
        jdbc.update("INSERT INTO estacion VALUES (?,'B',700,480,FALSE)", diseno);
        jdbc.update("INSERT INTO estacion VALUES (?,'C',?,?,FALSE)", diseno, geografia.posicionX(rambla), geografia.posicionY(rambla));
        jdbc.update("INSERT INTO linea VALUES (?,'Azul')", diseno);
        jdbc.update("INSERT INTO tramo VALUES (?,'Azul','A','B'),(?,'Azul','B','C')", diseno, diseno);
        for (String nombre : new String[]{"A", "B", "C"}) jdbc.update("INSERT INTO pasa VALUES (?,'Azul',?)", diseno, nombre);
        jdbc.update("INSERT INTO metro(id_diseno,nombre_linea) VALUES (?,'Azul')", diseno);
    }

    private void simular(int diseno) {
        jdbc.update("INSERT INTO simulacion(id_intento,comentarios) VALUES (?,?)", diseno, juego.marcaRedSimulada(diseno));
    }

    private ConsignaDisenoResponse consigna() { return juego.obtenerConsigna(usuario, 4); }
    private void reglas(String json) { jdbc.update("UPDATE escenario SET reglas_exito=? WHERE numero=4", json); }

    private void redAvanzada(int diseno, int nivel) throws Exception {
        var reglas = mapper.readTree(jdbc.queryForObject("SELECT reglas_exito FROM escenario WHERE numero=?", String.class, nivel));
        int cantidad = reglas.path("minimoEstaciones").asInt();
        int indice = 0;
        for (var objetivo : reglas.path("puntosInteresObjetivo")) {
            var poi = geografia.resolverPunto(objetivo.path("idPunto").asInt(), null);
            jdbc.update("INSERT INTO estacion VALUES (?,?,?,?,?)", diseno, "E" + indice++,
                RestriccionesGeograficasService.redondear(geografia.posicionX(poi)),
                RestriccionesGeograficasService.redondear(geografia.posicionY(poi)), false);
        }
        while (indice < cantidad) {
            jdbc.update("INSERT INTO estacion VALUES (?,?,?,?,FALSE)", diseno, "E" + indice, 660 + indice * 5, 460);
            indice++;
        }
        jdbc.update("INSERT INTO linea VALUES (?,'Principal')", diseno);
        jdbc.update("INSERT INTO metro(id_diseno,nombre_linea,velocidad_promedio) VALUES (?,'Principal',?)", diseno, reglas.path("puntuacion").path("velocidadObjetivoKmh").asInt(40));
        for (int i = 0; i < cantidad; i++) {
            jdbc.update("INSERT INTO pasa VALUES (?,'Principal',?)", diseno, "E" + i);
            if (i > 0) jdbc.update("INSERT INTO tramo VALUES (?,'Principal',?,?)", diseno, "E" + (i - 1), "E" + i);
        }
        int intercambios = reglas.path("minimoTransbordos").asInt();
        for (int i = 1; i < reglas.path("minimoLineas").asInt(); i++) {
            String linea = "Enlace" + i;
            String origen = "E" + (nivel == 10 ? i - 1 : 0);
            String destino = "E2";
            jdbc.update("INSERT INTO linea VALUES (?,?)", diseno, linea);
            jdbc.update("INSERT INTO metro(id_diseno,nombre_linea,velocidad_promedio) VALUES (?,?,?)", diseno, linea, reglas.path("puntuacion").path("velocidadObjetivoKmh").asInt(40));
            jdbc.update("INSERT INTO pasa VALUES (?,?,?),(?,?,?)", diseno, linea, origen, diseno, linea, destino);
            jdbc.update("INSERT INTO tramo VALUES (?,?,?,?)", diseno, linea, origen, destino);
        }
        for (int i = 0; i < intercambios; i++) {
            String nombre = "E" + (intercambios == 2 && i == 1 ? 2 : i);
            jdbc.update("UPDATE estacion SET transbordo=TRUE WHERE id_diseno=? AND nombre=?", diseno, nombre);
        }
    }

    @Test
    void administradorAccedeATodosLosNivelesYLibreSinPuntosAutomaticos() {
        jdbc.update("UPDATE usuario SET rol='ADMIN' WHERE id_usuario=7");
        jdbc.update("INSERT INTO escenario VALUES (11,NULL,'Libre','','','', 'EDICION_LIBRE',TRUE,'{}','{}')");
        jdbc.update("INSERT INTO intento VALUES (10,7,10,10,1,'EN_DESARROLLO',0,NULL,NULL)");
        jdbc.update("INSERT INTO intento VALUES (11,7,11,11,1,'EN_DESARROLLO',0,NULL,NULL)");
        var progreso = juego.obtenerResumenProgreso(7);
        assertTrue(progreso.escenarios().stream().allMatch(e -> e.desbloqueado()));
        assertTrue(progreso.modoLibreDesbloqueado());
        assertEquals(0, progreso.nivelesCompletados());
        assertEquals("EN_DESARROLLO", juego.iniciarEscenario(7, 10).estado());
        assertEquals(11, juego.iniciarEscenario(7, 11).idDiseno());
        assertEquals(0, jdbc.queryForObject("SELECT COUNT(*) FROM intento WHERE puntaje IS NOT NULL", Integer.class));
        jdbc.update("UPDATE usuario SET rol='JUGADOR' WHERE id_usuario=7");
        assertThrows(ResponseStatusException.class, () -> juego.iniciarEscenario(7, 10));
        assertFalse(juego.tieneModoLibreDesbloqueado(7));
    }

    @Test
    void velocidadEsComplementariaRequiereNuevaSimulacionYPreservaElMejorResultado() throws Exception {
        jdbc.update("INSERT INTO intento VALUES (6,7,6,6,1,'EN_DESARROLLO',0,NULL,NULL)");
        assertEquals(0, juego.obtenerDesempeno(7, 6).puntaje());
        redAvanzada(6, 6);
        jdbc.update("UPDATE metro SET velocidad_promedio=90 WHERE id_diseno=6");
        simular(6);
        assertEquals("VELOCIDAD", juego.obtenerDesempeno(7, 6).etapa());
        assertFalse(juego.evaluarEscenario(7, 6).completado());
        jdbc.update("UPDATE metro SET velocidad_promedio=45 WHERE id_diseno=6");
        assertEquals("SIMULACION", juego.obtenerDesempeno(7, 6).etapa());
        assertFalse(juego.evaluarEscenario(7, 6).completado());
        simular(6);
        var optimo = juego.evaluarEscenario(7, 6);
        assertTrue(optimo.completado()); assertEquals(100, optimo.puntaje());
        assertEquals(100, jdbc.queryForObject("SELECT puntaje FROM simulacion WHERE id_intento=6 ORDER BY id_simulacion DESC LIMIT 1", Integer.class));
        double minutos = optimo.desempeno().unidades().getFirst().tiempoMinutos();
        jdbc.update("UPDATE metro SET velocidad_promedio=60 WHERE id_diseno=6");
        assertTrue(juego.obtenerDesempeno(7, 6).unidades().getFirst().tiempoMinutos() < minutos);
        simular(6);
        var mejorable = juego.evaluarEscenario(7, 6);
        assertTrue(mejorable.completado()); assertEquals(90, mejorable.puntaje());
        assertEquals(90, jdbc.queryForObject("SELECT puntaje FROM simulacion WHERE id_intento=6 ORDER BY id_simulacion DESC LIMIT 1", Integer.class));
        assertEquals(100, jdbc.queryForObject("SELECT puntaje FROM intento WHERE id_intento=6", Integer.class));
        jdbc.update("UPDATE estacion SET posicion_x=0,posicion_y=0 WHERE id_diseno=6 AND nombre='E0'");
        assertEquals(0, juego.obtenerDesempeno(7, 6).puntaje());
        assertFalse(juego.evaluarEscenario(7, 6).completado());
    }

    @Test
    void economiaPenalizaElementosExtraYNoDependeDeDatosDelNavegador() throws Exception {
        red(1);
        var resultado = juego.evaluarEscenario(7, 1);
        assertTrue(resultado.completado());
        assertTrue(resultado.puntaje() < resultado.desempeno().puntajeMaximo());
        assertTrue(resultado.desempeno().puntosResolucion() >= resultado.desempeno().puntajeMaximo() * .6);
        assertEquals(0, resultado.desempeno().puntosVelocidad());
    }

    @Test
    void rankingSumaMejoresSinLibreNiAdministradoresYDesempataEstablemente() {
        jdbc.update("INSERT INTO usuario VALUES (8,1,FALSE,'JUGADOR'),(9,1,FALSE,'ADMIN')");
        jdbc.update("INSERT INTO escenario VALUES (11,NULL,'Libre','','','', 'EDICION_LIBRE',TRUE,'{}','{}')");
        jdbc.update("UPDATE intento SET estado='COMPLETADO',puntaje=80 WHERE id_intento=1");
        jdbc.update("INSERT INTO intento VALUES (12,7,1,12,1,'COMPLETADO',100,70,NULL),(13,7,11,13,1,'COMPLETADO',100,10000,NULL),(14,8,1,14,1,'COMPLETADO',100,80,NULL),(15,9,1,15,1,'COMPLETADO',100,9000,NULL)");
        var ranking = new PuntuacionService(jdbc, mapper, geografia).ranking(7);
        assertEquals(2, ranking.jugadores().size()); assertEquals(80, ranking.puntajeTotal());
        assertEquals(1, ranking.tuPosicion()); assertEquals(1000, ranking.puntajeMaximo());
        jdbc.update("UPDATE intento SET puntaje=90 WHERE id_intento=12");
        assertEquals(90, new PuntuacionService(jdbc, mapper, geografia).ranking(7).puntajeTotal());
    }

    @Test
    void diezNivelesTienenSolucionConGeografiaRealYProgresoPersistido() throws Exception {
        for (int nivel = 1; nivel <= 10; nivel++) {
            if (nivel > 4) jdbc.update("INSERT INTO intento VALUES (?,?,?, ?,1,'EN_DESARROLLO',0,NULL,NULL)", nivel, 7, nivel, nivel);
            assertFalse(juego.evaluarEscenario(7, nivel).completado(), "Una red vacía no resuelve " + nivel);
            if (nivel <= 4) red(nivel); else redAvanzada(nivel, nivel);
            if (nivel >= 4) simular(nivel);
            var consigna = juego.obtenerConsigna(usuario, nivel);
            assertTrue(consigna.condiciones().stream().allMatch(c -> c.completado()), "Nivel " + nivel + ": " + consigna.condiciones());
            var resultado = juego.evaluarEscenario(7, nivel);
            assertTrue(resultado.completado());
            assertEquals(nivel == 10 ? null : nivel + 1, resultado.idSiguienteEscenario());
            var resumen = juego.obtenerResumenProgreso(7);
            assertEquals(10, resumen.cantidadNiveles());
            assertEquals(nivel, resumen.nivelesCompletados());
            assertEquals(nivel == 10, resumen.campanaCompletada());
            assertEquals(nivel == 10, resumen.modoLibreDesbloqueado());
            if (nivel < 10) assertTrue(resumen.escenarios().get(nivel).desbloqueado());
            if (nivel < 9) assertFalse(resumen.escenarios().get(nivel + 1).desbloqueado());
        }
        assertEquals(409, assertThrows(ResponseStatusException.class, () -> juego.iniciarEscenario(7, 10)).getStatusCode().value());
        var reinicio = juego.reiniciarRecorrido(7, 1);
        assertEquals(0, reinicio.nivelesCompletados());
        assertEquals(2, reinicio.numeroCampanaActual());
        assertTrue(reinicio.modoLibreDesbloqueado());
        assertEquals(10, jdbc.queryForObject("SELECT COUNT(*) FROM intento WHERE estado='COMPLETADO'", Integer.class));
        assertFalse(reinicio.escenarios().get(9).desbloqueado());
    }

    @Test
    void cadaNuevoNivelRechazaUnaRedQueResuelveElAnteriorYElLimiteEsReal() throws Exception {
        for (int nivel = 5; nivel <= 10; nivel++) {
            jdbc.update("INSERT INTO intento VALUES (?,?,?, ?,1,'EN_DESARROLLO',0,NULL,NULL)", nivel, 7, nivel, nivel);
            if (nivel == 5) red(nivel); else redAvanzada(nivel, nivel - 1);
            simular(nivel);
            if (nivel == 9) {
                // Conservar los conteos del nivel 8, pero alejar 15 unidades una estación de su POI.
                jdbc.update("UPDATE estacion SET posicion_y=posicion_y-15 WHERE id_diseno=9 AND nombre='E2'");
            }
            assertFalse(juego.obtenerConsigna(usuario, nivel).condiciones().stream().allMatch(c -> c.completado()), "La red anterior no debe bastar para " + nivel);
        }
        jdbc.update("INSERT INTO estacion VALUES (9,'ExtraA',700,460,FALSE),(9,'ExtraB',710,460,FALSE)");
        assertFalse(juego.obtenerConsigna(usuario, 9).condiciones().stream()
            .filter(c -> c.clave().equals("maximoEstaciones")).findFirst().orElseThrow().completado());
    }

    @Test
    void unIntentoAdelantadoNoDesbloqueaNivelesConPredecesoresFaltantes() {
        jdbc.update("UPDATE intento SET estado='COMPLETADO',progreso=100 WHERE id_intento=4");
        var resumen = juego.obtenerResumenProgreso(7);
        assertFalse(resumen.escenarios().get(4).desbloqueado());
        assertFalse(resumen.campanaCompletada());
        assertEquals(403, assertThrows(ResponseStatusException.class, () -> juego.iniciarEscenario(7, 5)).getStatusCode().value());
    }

    @Test
    void cuatroNivelesConservanHerramientasYProgresionYPersistenIntentos() throws Exception {
        assertEquals(403, assertThrows(ResponseStatusException.class, () -> juego.iniciarEscenario(7, 2)).getStatusCode().value());
        for (int nivel = 1; nivel <= 4; nivel++) {
            assertFalse(juego.evaluarEscenario(7, nivel).completado());
            red(nivel);
            if (nivel < 4) {
                assertTrue(juego.obtenerConsigna(usuario, nivel).referenciasObjetivo().isEmpty());
                var herramientas = mapper.readTree(jdbc.queryForObject("SELECT herramientas_habilitadas FROM escenario WHERE numero=?", String.class, nivel));
                assertFalse(herramientas.path("simulacion").asBoolean());
                assertEquals(nivel >= 2, herramientas.path("conexiones").asBoolean());
                assertEquals(nivel >= 3, herramientas.path("metros").asBoolean());
            } else {
                assertFalse(juego.evaluarEscenario(7, 4).completado());
                assertEquals(2, consigna().referenciasObjetivo().size());
                simular(4);
            }
            var resultado = juego.evaluarEscenario(7, nivel);
            assertTrue(resultado.completado(), "Nivel " + nivel);
            assertEquals(100, resultado.progreso());
            assertEquals("COMPLETADO", jdbc.queryForObject("SELECT estado FROM intento WHERE id_intento=?", String.class, nivel));
            assertNotNull(jdbc.queryForObject("SELECT fecha_finalizacion FROM intento WHERE id_intento=?", java.sql.Timestamp.class, nivel));
            if (nivel < 4) assertEquals(nivel + 1, juego.iniciarEscenario(7, nivel + 1).idDiseno());
        }
        assertFalse(jdbc.queryForObject("SELECT campana_completada_historicamente FROM usuario", Boolean.class));
        assertEquals(5, juego.evaluarEscenario(7, 4).idSiguienteEscenario());
        var reiniciado = juego.reiniciarRecorrido(7, 1);
        assertEquals(2, reiniciado.numeroCampanaActual());
        assertEquals(0, reiniciado.nivelesCompletados());
        assertEquals(4, jdbc.queryForObject("SELECT COUNT(*) FROM intento WHERE estado='COMPLETADO'", Integer.class));
        assertEquals(409, assertThrows(ResponseStatusException.class, () -> juego.evaluarEscenario(7, 4)).getStatusCode().value());
    }

    @Test
    void combinaCoberturaRecorridoYAreasYDetectaDesplazamientos() {
        red(4);
        simular(4);
        assertTrue(consigna().condiciones().stream().allMatch(c -> c.completado()));
        jdbc.update("UPDATE estacion SET posicion_x=0,posicion_y=0 WHERE id_diseno=4 AND nombre='C'");
        assertFalse(consigna().referenciasObjetivo().get(1).cubierto());
        assertFalse(consigna().condiciones().stream().filter(c -> c.clave().equals("requiereObjetivosMismaLinea")).findFirst().orElseThrow().completado());
        assertFalse(juego.evaluarEscenario(7, 4).completado());
    }

    @Test
    void unPoiSeValidaYUnaReferenciaInexistenteNoSeIgnoraAunqueElOtroEsteCubierto() {
        red(4);
        reglas("{\"requiereCoberturaPuntosInteres\":true,\"puntosInteresObjetivo\":[{\"idPunto\":1,\"radioCobertura\":60}]}");
        assertEquals("LISTO", consigna().estadoGlobal());
        reglas("{\"requiereCoberturaPuntosInteres\":true,\"puntosInteresObjetivo\":[{\"idPunto\":1,\"radioCobertura\":60},{\"idPunto\":9999,\"radioCobertura\":60}]}");
        assertTrue(consigna().condiciones().stream().anyMatch(c -> c.clave().equals("configuracionPuntosInteres") && !c.completado()));
        assertFalse(juego.evaluarEscenario(7, 4).completado());
    }

    @Test
    void barriosYTransbordosSonReglasOptativasVerificables() {
        red(4);
        reglas("{\"areasObjetivo\":[{\"tipo\":\"barrio\",\"nombre\":\"AGUADA\"}],\"minimoTransbordos\":1}");
        assertTrue(consigna().condiciones().stream().filter(c -> c.clave().startsWith("areaObjetivo")).findFirst().orElseThrow().completado());
        assertFalse(juego.evaluarEscenario(7, 4).completado());
        jdbc.update("UPDATE estacion SET transbordo=TRUE WHERE nombre='A'");
        assertFalse(juego.evaluarEscenario(7, 4).completado());
        jdbc.update("INSERT INTO linea VALUES (4,'Roja')");
        jdbc.update("INSERT INTO pasa VALUES (4,'Roja','A')");
        assertTrue(juego.evaluarEscenario(7, 4).completado());
        reglas("{\"areasObjetivo\":[{\"tipo\":\"barrio\",\"nombre\":\"Sin geometría\"}]}");
        assertFalse(juego.evaluarEscenario(7, 4).completado());
        assertTrue(consigna().condiciones().getFirst().texto().contains("sin geometría"));
    }
}
